# systemd-journal-upload
etc/systemd/journal-upload.conf
usr/lib/systemd/systemd-journal-upload
usr/lib/systemd/system/systemd-journal-upload.service
usr/share/man/man5/journal-upload.conf.d.5
usr/share/man/man5/journal-upload.conf.5

# systemd-journal-remote
etc/systemd/journal-remote.conf
usr/lib/systemd/systemd-journal-remote
usr/lib/systemd/system/systemd-journal-remote.service
usr/lib/systemd/system/systemd-journal-remote.socket
usr/share/man/man8/systemd-journal-remote.8
usr/share/man/man5/journal-remote.conf.d.5
usr/share/man/man5/journal-remote.conf.5

# systemd-journal-gatewayd
usr/lib/systemd/systemd-journal-gatewayd
usr/lib/systemd/system/systemd-journal-gatewayd.service
usr/lib/systemd/system/systemd-journal-gatewayd.socket
usr/share/systemd/gatewayd/
usr/share/man/man8/systemd-journal-gatewayd.service.8
usr/share/man/man8/systemd-journal-gatewayd.socket.8
usr/share/man/man8/systemd-journal-gatewayd.8
